# Generated by Django 3.0.5 on 2020-06-13 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tblcommonmasters',
            fields=[
                ('autoid', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.TextField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('isactive', models.IntegerField(blank=True, null=True)),
                ('image_url', models.CharField(blank=True, max_length=250, null=True)),
                ('type', models.CharField(blank=True, max_length=50, null=True)),
                ('userid', models.IntegerField(blank=True, null=True)),
                ('createdon', models.DateTimeField(blank=True, null=True)),
                ('otherfield', models.CharField(blank=True, max_length=1000, null=True)),
            ],
        ),
    ]
