# Generated by Django 3.0.5 on 2020-06-13 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shubham', '0002_tbloptions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbloptions',
            name='github_link',
            field=models.CharField(max_length=300, null=True),
        ),
    ]
