# Generated by Django 3.0.5 on 2020-06-13 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shubham', '0003_auto_20200613_2105'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbloptions',
            name='images',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
