# Generated by Django 3.0.5 on 2020-06-13 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shubham', '0004_tbloptions_images'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbloptions',
            name='images',
            field=models.ImageField(null=True, upload_to='shubham/images'),
        ),
    ]
